[package]
name = "pcbparts-search"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
regex = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
pcbparts-parsers = { path = "../pcbparts-parsers" }
pcbparts-db = { path = "../pcbparts-db" }
